### ISSUE TITLE
npm start returns error

### ISSUE THREAD

**Issue by dmitryponv** [BretCameron/three-js-sample#4]
I installed nodejs on Windows 10 and added it to environment variable Path
Did a git clone of your project

Running `npm start` gives me the following error

Do you know what is missing? Maybe you can add this to the readme html since your project is intended to be an example for beginners. Thanks, 

```
c:\Dev\Projects\hree-js-sample>npm start

> three-js-sample@0.1.0 start c:\Dev\Projects\BlazeDAW\three-js-sample
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! three-js-sample@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the three-js-sample@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Garage\AppData\Roaming\npm-cache\_logs\2020-07-14T05_22_37_112Z-debug.log
```

**Comment by BretCameron** [comment]
Hi @dmitryponv, this project uses Yarn, so you'll need to:

**1. install yarn globally**

```sh
npm install -g yarn
```

**2. navigate to the project folder in your terminal and run**

```sh
yarn
```

You should then be able to run `yarn start` to see the project. Let me know if this helps and - if so - I'll update the README.

**Comment by dmitryponv** [comment]
Thanks, will close issue
